id: PB30CDCB5
initial_creation_type: ocr
source_metadata:
  volumes:
    bfc7d9b42dd648bd821176b773621f3e:
      base_file: v043.txt
      image_group_id: I1PD95888
      title: ''
      total_pages: 1379
      volume_number: 43
